index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }

user:
    resource: "routing_user.yaml"

# Depends on sensio/framework-extra-bundle:^3.0 and doctrine/annotations
#controllers:
#    resource: ../src/App/Controller/
#    type: annotation
