index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }

user:
    resource: "routing/user.yaml"

article:
    resource: "routing/article.yaml"

room:
    resource: "routing/room.yaml"
