<?php

namespace App\Repository;

use App\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findByCategory(Category $category)
    {
        return $this->createQueryBuilder('a')
            ->join('a.categories', 'c')
            ->where('c.id = :category')->setParameter('category', $category->getId())
            ->orderBy('a.updatedAt', 'DESC');
    }
}
