<?php

namespace App\Repository;

use App\Entity\Article;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends EntityRepository
{
    public function exist(User $user, Article $article): QueryBuilder
    {
        return $this->createQueryBuilder('f')
            ->where('f.userId = :user')->setParameter('user', $user->getId())
            ->andWhere('f.articleId = :article')->setParameter('article', $article->getId());
    }
}
