<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use App\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    protected function prepare(int $status = User::ACTIVE): QueryBuilder
    {
        $query = $this->createQueryBuilder('u')
            ->select('u.id AS user_id')
            ->addSelect('u.username AS user_username');

        if ($status !== false) {
            $query = $query->where('u.active = :status')->setParameter('status', $status);
        }

        return $query;
    }

    public function getByUsernameOrEmail(string $username): QueryBuilder
    {
        return $this->prepare()
            ->andWhere('u.username = :username')
            ->orWhere('u.email = :username')->setParameter('username', $username);
    }
}
