security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: App\Security\UserProvider

    encoders:
        App\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator

    access_control:
        -
          path:                       "^(/[a-zA-Z]{2})?/user/"
          roles:                      ROLE_USER
        -
          path:                       "^(/[a-zA-Z]{2})?/admin/"
          roles:                      ROLE_ADMIN

    role_hierarchy:
        ROLE_USER:	                  []
        ROLE_ADMIN:	                  [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
